create table tb_worker (id int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id));
create table tb_worker (id int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id));
